### ISSUE TITLE
Adding bundle to the shopping cart

### ISSUE THREAD

**Issue by piotrpog** [KuriousAgency/commerce-bundles#1]
How can i add bundle to the shopping cart?

**Comment by mcjackson18** [comment]
@piotrpog, on your bundle page you will have access to the `bundle` variable. 

You can then use the standard Craft Commerce add to cart form (see example here https://craftcms.com/docs/commerce/2.x/adding-to-and-updating-the-cart.html) replacing `<input type="hidden" name="purchasableId" value="{{ variant.id }}">` with `<input type="hidden" name="purchasableId" value="{{ bundle.id }}">`

**Comment by piotrpog** [comment]
@mcjackson18 
Thanks!
