### ISSUE TITLE
Error Setting unknown property: webdna\commerce\bundles\elements\db\BundleQuery::enabledForSite

### ISSUE THREAD

**Issue by IruneItoiz** [KuriousAgency/commerce-bundles#15]
I keep getting this error when I try to save bundles or when I try to save a site. CraftCMS and Craft Commerce 4.

Also not letting me edit bundles, not sure if it's related to permissions by site?

**Comment by JeffHarbers** [comment]
I am experiencing the same error and can not edit any bundles using CraftCMS 4 + Commerce 4.

**Comment by meinhard-meintjes** [comment]
Same here

**Comment by gijsstegehuis** [comment]
Same same.

Opened a PR for this. See https://github.com/webdna/commerce-bundles/pull/18

**Comment by samuelbirch** [comment]
fixed in 2.0.0-beta.6
