### ISSUE TITLE
Can't resave Bundle Type

### ISSUE THREAD

**Issue by HAWilliams01** [KuriousAgency/commerce-bundles#16]
Unable to edit (add or remove fields) or re-save a bundle type after it is created

![Screenshot 2023-05-23 at 11 14 46 AM](https://github.com/webdna/commerce-bundles/assets/35875559/3813091b-7626-4de9-8859-dd2a6e9d8b6a)

**Comment by samuelbirch** [comment]
this should be fixed 2.0.0-beta.6
