### ISSUE TITLE
[FR] Bundle list in control panel - link to bundle missing

### ISSUE THREAD

**Issue by piotrpog** [KuriousAgency/commerce-bundles#2]
I checked in "customize" screen of bundle list (cogwheel icon) and there is no option for adding bundle link (like entries have - globe icon) as column of list.

**Comment by mcjackson18** [comment]
@piotrpog, we'll add this to the roadmap for a future release.

**Comment by mcjackson18** [comment]
@piotrpog, the link has been added in 1.1.4.
