### ISSUE TITLE
How to get bundles related to a product

### ISSUE THREAD

**Issue by chadcrowell** [KuriousAgency/commerce-bundles#3]
I feel like I must be missing something... I don't want to show bundles on their own page, I want to show any bundles that include the product currently being viewed. Getting the bundles that include the current product looks like this:

```
{# Get the default product variant #}
{% set variant = product.defaultVariant %}
{# Get any bundles associated with this variant #}
{% set bundles = [] %}
{% set allBundles = craft.bundles() ?? null %}
{% for bundle in allBundles.all() %}
	{% set bundleProducts = bundle.getProducts() %}
	{% for bundleProduct in bundleProducts %}
		{% if bundleProduct.id == variant.id %}
			{% set bundles = bundles|merge([bundle]) %}
		{% endif %}
	{% endfor %}
{% endfor %}
```

That seems like a very long way to go. I see there is no record for the bundles in the craft_relations table, so I can't use 

```
{% set bundles = craft.bundles().relatedTo(variant) ?? null %}
```

but something short like that would be desired. Is there a better way?

**Comment by mcjackson18** [comment]
Hi @chadcrowell, verison 1.1.7 adds purchasableIds & purchasables parameter to the element query -`craft.bundles.purchasables().all()`
