### ISSUE TITLE
Add isBundle()

### ISSUE THREAD

**Issue by chadcrowell** [KuriousAgency/commerce-bundles#4]
Is it possible to add a variable I can use in places like the shopping cart:

```
{% for item in cart.lineItems %}
    {%if item.isBundle() %}
        do something...
    {% endif %}
{% endfor %}
``` 

edit: Both Events and Gift Vouchers by Verbb have this variable, if you need some direction on how to implement.

[Events](https://github.com/verbb/events)

[Gift Vouchers](https://github.com/verbb/gift-voucher)

**Comment by mcjackson18** [comment]
@chadcrowell, we'll add this to the roadmap for a future release, thanks for the examples.

**Comment by piotrpog** [comment]
@chadcrowell 
As a walkaround, you can output classname of element and check if it is a product or bundle.

https://craftcms.com/docs/3.x/dev/functions.html#classname

**Comment by mcjackson18** [comment]
@chadcrowell, you can now check if a line item is bundle using `craft.commerceBundles.bundles.isBundle(lineItem)`.
