### ISSUE TITLE
Bundle::hasUnlimitedStock

### ISSUE THREAD

**Issue by chadcrowell** [KuriousAgency/commerce-bundles#7]
I've got a commerce site using bundles that uses hasUnlimitedStock for quite a bit of logic throughout the checkout process. It appears that Bundle elements don't have this property currently, which, when checking out, allows the order to be placed, but throws this error and doesn't take the customer from the payment page to the order summary page.

`Getting unknown property: kuriousagency\commerce\bundles\elements\Bundle::hasUnlimitedStock`

[View example](https://d.pr/i/vkWQJG)

By hacking the elements/Bundle.php file and adding `public $hasUnlimitedStock;` after line 75, the error goes away and order completes as expected. Is it possible you could add this property so I don't have to hack future versions of this plugin?

**Comment by samuelbirch** [comment]
closing as out of date
